spring:
    application:
        name: vehicle-index-backend
    datasource:
        url: ENC(QpWhOx1mhRxyGQuMZfgP4iL3QWvn0hYN+C7/HuZxkVy0HEG1dwxfaWzblmNJsWOLvKF4Vt3MFwAc5DSaT4qYibIGcJD5vLISUuVLyS9nCz5nC5O1JeAARnR/Q9wsA6J0c07P9bjk5dQ=)
        username: ENC(uI/Aiqxd7i1dQjJTAxZ65Q==)
        password: ENC(QALXGxG5g3hdRa54iLQXQQrwyZvgvnxGjPmlbXnALPM=)
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: true  #display the actual query ran in the console
        properties:
            hibernate:
                jdbc:
                    batch_size: 50                  # Group up to 50 inserts
                order_inserts: true             # Required for batching
#                generate_statistics: true
#                format_sql: true
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: validate


jasypt:
    encryptor:
        algorithm: PBEWithMD5AndDES
        iv-generator-classname: org.jasypt.iv.NoIvGenerator